# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_helloWorld',
                'doc_host': 'https://lesterw53679.github.io',
                'git_url': 'https://github.com/lesterw53679/nbdev_helloWorld',
                'lib_path': 'nbdev_helloWorld'},
  'syms': {'nbdev_helloWorld.core': {'nbdev_helloWorld.core.foo': ('core.html#foo', 'nbdev_helloWorld/core.py')}}}
